process.stdout.write("*\n");
process.stdout.write("**\n");
process.stdout.write("***\n");
process.stdout.write("****\n");
process.stdout.write("*****\n");
console.log('-------------');
process.stdout.write("*****\n");
process.stdout.write("****\n");
process.stdout.write("***\n");
process.stdout.write("**\n");
process.stdout.write("*\n");
console.log('-------------');
process.stdout.write("    *\n");
process.stdout.write("   ***\n");
process.stdout.write("  *****\n");
process.stdout.write(" *******\n");
process.stdout.write("*********\n");
console.log('-------------');
process.stdout.write("*********\n");
process.stdout.write(" *******\n");
process.stdout.write("  *****\n");
process.stdout.write("   ***\n");
process.stdout.write("    *\n");